FROM python:3.11-slim

WORKDIR /app

ENV KAFKA_SERVER=broker
ENV HOST=mongodb
ENV COLLECTION=interesting

ENV TOPIC=interesting
ENV EXPOSE_PORT=8082

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

copy . .

EXPOSE 8082

CMD ["python","main.py"]